server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /service      #统一前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept      #微服务映射
    mydept.path: /mydept/**

info:
  app.name: ljc-microcloud
  company.name: www.ljc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
